controller:
  ingress:
    enabled: true
    apiVersion: networking.k8s.io/v1
    annotations:
      ingressClassName: nginx
      kubernetes.io/tls-acme: "true"
    hostName: jenkins.lab.quanby.nl
    tls:
      - secretName: tls-jenkins-ingress
        hosts:
          - jenkins.lab.quanby.nl
  installPlugins:
  - kubernetes:1.29.4
  - workflow-aggregator:2.6
  - git:4.7.1
  - configuration-as-code:1.51
  - blueocean:1.24.6
persistence:
  storageClass: longhorn
